---
label: App Config
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: name
- name: location
  type: text
  config:
    required: true
  label: location
  default: The Internet
- name: bio
  type: text
  config:
    required: true
  label: bio
- name: avatar
  type: file
  config:
    maxSize: 64
  label: avatar
- name: repo
  type: text
  config:
    required: false
  label: repo
  description: URL to the git repository.
- name: theme
  type: field_group
  config: {}
  fields:
  - name: dark
    type: boolean
    label: dark
    description: Use dark theme instead of light theme.
  - name: skew
    type: boolean
    label: skew
    default: true
    description: Should the background image be cut diagonally.
  - name: color
    type: text
    config:
      required: true
    label: color
    default: blue
    description: Color to use for contacts backgrounds (on light theme) and footer
      icons. See <a href="https://tailwindcss.com/docs/customizing-colors#default-color-palette"
      title="TailwindCSS" target="_blank">https://tailwindcss.com/docs/customizing-colors#default-color-palette</a>
      for a preview of the colors.
  - name: background
    type: file
    config:
      maxSize: 64
    label: background
  - name: contacts
    type: field_group
    config: {}
    fields:
    - name: name
      type: boolean
      label: name
      default: true
      description: Show the contact's name.
    - name: rounded
      type: boolean
      label: rounded
      description: Makes the contact a pill if the name is shown, or a circle if it's
        not.
    - name: allsame
      type: boolean
      label: all-same
      default: true
      description: Shows all the contact the same way, instead of showing the first
        bigger when having more than 3.
    - name: full
      type: boolean
      label: full
      default: true
      description: Show a background instead of a border.
    label: contacts
  - name: repo
    type: boolean
    label: repo
    default: true
    description: Show the icon/link to the repository inside the footer.
  - name: footer
    type: boolean
    label: footer
    default: true
    hidden: false
    description: Show the footer.
  - name: favicon
    type: file
    config:
      maxSize: 64
    label: favicon
    default: "/uploads/at.svg"
  label: theme
- name: content
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: name
    description: The link name or the section's title. <br>Not used for embeds.
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: content
    description: Used as text in content or as description under links.
  - name: url
    type: text
    config:
      required: false
    label: url
  - name: invert
    type: boolean
    label: invert
    default: false
    description: Invert the colors of the uploaded image (Useful for SVG images).
  - name: darker
    type: boolean
    label: darker
    default: false
  - name: image
    type: file
    config:
      maxSize: 64
    label: image
    default: "/uploads/icon.svg"
  - name: color
    type: text
    config:
      required: false
    label: color
    default: gray
    description: Color to use for contacts backgrounds (on light theme) and footer
      icons. See <a href="https://tailwindcss.com/docs/customizing-colors#default-color-palette"
      title="https://tailwindcss.com/docs/customizing-colors#default-color-palette"
      target="_blank">https://tailwindcss.com/docs/customizing-colors#default-color-palette</a>
      for a preview of the colors.
  - name: classes
    type: text
    config:
      required: false
    label: classes
    description: Additional tailwind classes to apply to the link's image.
  - name: type
    type: select
    default: link
    config:
      required: false
      options:
      - link
      - embed
      - section
      - content
      source:
        type: simple
        section: 
        file: 
        path: 
    label: type
  config:
    min: 
    max: 
    labelField: name
  label: content
- name: contacts
  type: field_group_list
  fields:
  - name: icon
    type: text
    config:
      required: true
    label: icon
    default: account-box
    description: The contact' icon. See <a href="https://materialdesignicons.com/"
      title="https://materialdesignicons.com/" target="_blank">https://materialdesignicons.com/</a>
      for a list of all the icons.
  - name: name
    type: text
    config:
      required: true
    label: name
  - name: uri
    type: text
    config:
      required: true
    label: uri
    description: The url to the contact, with relative protocol (like "mailto:" for
      emails or "tel:" for telephone numbers).
  - name: image
    type: file
    config:
      maxSize: 64
    label: image
    default: ''
  label: contacts
- name: custom_css
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: custom css
- name: custom_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: customcontent
  description: Can be used to add scripts to the end of the page, like tracking. For
    open-source analytics, we suggests you to try Plausible or Matomo.
- name: footer_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: footercontent
  description: Stuff to add to the center of the footer.
pages:
- config/app.json
